blueprint:
  name: "TADO Hijack automatic update Entity Offset with Switch ðŸ”¥ðŸŒ¡ï¸"
  description: >
    Update the offset attribute of an entity based on another sensor's state, with an on/off control.
  domain: automation

  input:
    sensor_to_monitor:
      name: Zigbee Sensor to Monitor
      description: The sensor whose state will be used to update the "offset" attribute
      selector:
        entity:
          domain:
            - sensor
          device_class:
            - temperature
          multiple: false

    climate_entity:
      name: Tado Homekit Entity
      description: The homekit TADO climate entity
      selector:
        entity:
          domain:
            - climate
          multiple: false

    entity_to_update:
      name: Tado Hijack offset entity
      description: The number entity for climate "offset"
      selector:
        entity:
          domain:
            - number
          multiple: false

    threshold:
      name: Threshold
      description: The maximum difference between the two sensors to trigger the automation
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: Â°C
          mode: slider

    start_time:
      name: When the automation starts.
      selector:
        time: {}

    end_time:
      name: When the automation stops.
      selector:
        time: {}

    time_interval_minutes:
      name: Time Interval (minutes)
      description: The interval in minutes for the calibration to trigger
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

    enable_switch:
      name: Enable Automation only when Heating
      description: Enable or disable the automation only when entity is on HEAT status
      default: true
      selector:
        boolean: {}

  source_url: https://github.com/davidepanato/ha-bp-tado-hj-control/blob/main/temp_sensor_calibration.yaml

variables:
  climate_entity: !input climate_entity
  entity_to_update: !input entity_to_update
  sensor_to_monitor: !input sensor_to_monitor
  interval: !input time_interval_minutes
  enable_switch: !input enable_switch

trigger:
  # Original calibration timer trigger
  - trigger: time_pattern
    minutes: "/1"
    id: calibrate

action:
  - choose:
      - conditions:
          - condition: trigger
            id: calibrate
          - condition: and
            conditions:
              - condition: time
                after: !input start_time
                before: !input end_time
              - condition: template
                value_template: >
                  {{ (now().minute % interval | int) == 0 }}
              - condition: or
                conditions:
                  - condition: template
                    value_template: "{{ enable_switch == false }}"
                  - condition: and
                    conditions:
                      - condition: template
                        value_template: "{{ enable_switch == true }}"
                      - condition: state
                        entity_id: !input climate_entity
                        attribute: hvac_action
                        state: heating
        sequence:
          - if:
              - condition: numeric_state
                entity_id:
                  - !input sensor_to_monitor
                value_template: >
                  {{ (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))|abs }}
                above: !input threshold
            then:
              - service: number.set_value
                data:
                  value: >
                    {{
                      ( states(entity_to_update)|float(0)
                        if states(entity_to_update) is not none else 0
                      )
                      +
                      (
                        (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))
                        if states(sensor_to_monitor) is not none and state_attr(climate_entity,'current_temperature') is not none
                        else 0
                      )
                      | round(1)
                    }}
                target:
                  entity_id: !input entity_to_update

trace:
  stored_traces: 240








