blueprint:
  name: "TADO Hijack automatic update Entity Offset with Switch + Manual Push"
  description: >
    Update the offset attribute of an entity based on another sensor's state, with an on/off control and optional manual push button.
    Optimized to run only at specified intervals instead of every minute, with stale-sensor failsafes.
  domain: automation

  input:
    sensor_to_monitor:
      name: Zigbee Sensor to Monitor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    climate_entity:
      name: Tado Homekit Entity
      selector:
        entity:
          domain: climate

    entity_to_update:
      name: Tado Hijack offset entity
      selector:
        entity:
          domain: number

    manual_trigger:
      name: Manual Push Button (Optional)
      description: Create as a Helper -> Input button (recommended). Leave empty to disable manual push.
      default: ""
      selector:
        entity:
          domain: input_button

    manual_ignore_failsafe:
      name: Manual push ignores failsafe (not recommended)
      description: If enabled, manual push can run even if sensor is stale/unavailable.
      default: false
      selector:
        boolean: {}

    sensor_max_age_minutes:
      name: Maximum Sensor Age (minutes)
      default: 10
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes

    threshold:
      name: Threshold
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: °C

    start_time:
      name: When the automation starts
      selector:
        time: {}

    end_time:
      name: When the automation stops
      selector:
        time: {}

    time_interval_minutes:
      name: Time Interval
      default: "/15"
      selector:
        select:
          options:
            - label: "Every 5 minutes"
              value: "/5"
            - label: "Every 10 minutes"
              value: "/10"
            - label: "Every 15 minutes"
              value: "/15"
            - label: "Every 20 minutes"
              value: "/20"
            - label: "Every 25 minutes"
              value: "/25"
            - label: "Every 30 minutes"
              value: "/30"
            - label: "Every 35 minutes"
              value: "/35"
            - label: "Every 40 minutes"
              value: "/40"
            - label: "Every 45 minutes"
              value: "/45"
            - label: "Every 50 minutes"
              value: "/50"
            - label: "Every 55 minutes"
              value: "/55"
            - label: "Every 60 minutes"
              value: "/60"

    enable_switch:
      name: Enable Automation only when Heating
      default: true
      selector:
        boolean: {}

variables:
  climate_entity: !input climate_entity
  entity_to_update: !input entity_to_update
  sensor_to_monitor: !input sensor_to_monitor
  enable_switch: !input enable_switch
  sensor_max_age_minutes: !input sensor_max_age_minutes
  manual_ignore_failsafe: !input manual_ignore_failsafe
  manual_trigger: !input manual_trigger

trigger:
  - trigger: time_pattern
    minutes: !input time_interval_minutes
    id: calibrate

  # Optional manual trigger: only fires if manual_trigger is set
  - trigger: state
    entity_id: !input manual_trigger
    id: manual_push

action:
  - choose:
      # Manual push (bypass time + interval, but keep failsafe unless overridden)
      - conditions:
          - condition: trigger
            id: manual_push
          - condition: template
            value_template: "{{ manual_trigger != '' }}"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ manual_ignore_failsafe }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ has_value(sensor_to_monitor) }}"
                  - condition: template
                    value_template: >
                      {% set s = states[sensor_to_monitor] if states[sensor_to_monitor] is defined else none %}
                      {% if s is none %}
                        false
                      {% else %}
                        {{ ((as_timestamp(now()) - as_timestamp(s.last_updated)) / 60) <= (sensor_max_age_minutes | float(0)) }}
                      {% endif %}
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ enable_switch == false }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ enable_switch == true }}"
                  - condition: state
                    entity_id: !input climate_entity
                    attribute: hvac_action
                    state: heating
        sequence:
          - if:
              - condition: numeric_state
                entity_id: !input sensor_to_monitor
                value_template: >
                  {{ (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))|abs }}
                above: !input threshold
            then:
              - service: number.set_value
                target:
                  entity_id: !input entity_to_update
                data:
                  value: >
                    {{
                      (states(entity_to_update)|float(0) if states(entity_to_update) is not none else 0)
                      +
                      (
                        (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))
                        if states(sensor_to_monitor) is not none and state_attr(climate_entity,'current_temperature') is not none
                        else 0
                      )
                      | round(1)
                    }}

      # Automatic calibration (failsafe always on + time window)
      - conditions:
          - condition: trigger
            id: calibrate
          - condition: template
            value_template: "{{ has_value(sensor_to_monitor) }}"
          - condition: template
            value_template: >
              {% set s = states[sensor_to_monitor] if states[sensor_to_monitor] is defined else none %}
              {% if s is none %}
                false
              {% else %}
                {{ ((as_timestamp(now()) - as_timestamp(s.last_updated)) / 60) <= (sensor_max_age_minutes | float(0)) }}
              {% endif %}
          - condition: time
            after: !input start_time
            before: !input end_time
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ enable_switch == false }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ enable_switch == true }}"
                  - condition: state
                    entity_id: !input climate_entity
                    attribute: hvac_action
                    state: heating
        sequence:
          - if:
              - condition: numeric_state
                entity_id: !input sensor_to_monitor
                value_template: >
                  {{ (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))|abs }}
                above: !input threshold
            then:
              - service: number.set_value
                target:
                  entity_id: !input entity_to_update
                data:
                  value: >
                    {{
                      (states(entity_to_update)|float(0) if states(entity_to_update) is not none else 0)
                      +
                      (
                        (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))
                        if states(sensor_to_monitor) is not none and state_attr(climate_entity,'current_temperature') is not none
                        else 0
                      )
                      | round(1)
                    }}

trace:
  stored_traces: 240
