blueprint:
  name: "TADO Hijack automatic update Entity Offset with Switch + Manual Push"
  description: >
    Update the offset attribute of an entity based on another sensor's state, with an on/off control and optional manual push button. Optimized to run only at specified intervals instead of every minute. 
  domain: automation

  input:
    sensor_to_monitor:
      name: Zigbee Sensor to Monitor
      description: The sensor whose state will be used to update the "offset" attribute
      selector:
        entity:
          domain:
            - sensor
          device_class:
            - temperature
          multiple: false

    climate_entity:
      name: Tado Homekit Entity
      description: The homekit TADO climate entity
      selector:
        entity:
          domain:
            - climate
          multiple: false

    entity_to_update:
      name: Tado Hijack offset entity
      description: The number entity for climate "offset"
      selector:
        entity:
          domain:
            - number
          multiple: false

    manual_trigger:
      name: Manual Push Button (Optional)
      description: A button or input_button entity to manually trigger calibration immediately, bypassing time and interval restrictions
      default: {}
      selector:
        entity:
          domain:
            - button
            - input_button
          multiple: false

    threshold:
      name: Threshold
      description: The maximum difference between the two sensors to trigger the automation
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: °C
          mode: slider

    start_time:
      name: When the automation starts
      selector:
        time: {}

    end_time:
      name: When the automation stops
      selector:
        time: {}

    time_interval_minutes:
      name: Time Interval
      description: How often to run the calibration check
      default: "/15"
      selector:
        select:
          options:
            - label: "Every 5 minutes"
              value: "/5"
            - label: "Every 10 minutes"
              value: "/10"
            - label: "Every 15 minutes"
              value: "/15"
            - label: "Every 20 minutes"
              value: "/20"
            - label: "Every 25 minutes"
              value: "/25"
            - label: "Every 30 minutes"
              value: "/30"
            - label: "Every 35 minutes"
              value: "/35"
            - label: "Every 40 minutes"
              value: "/40"
            - label: "Every 45 minutes"
              value: "/45"
            - label: "Every 50 minutes"
              value: "/50"
            - label: "Every 55 minutes"
              value: "/55"
            - label: "Every 60 minutes"
              value: "/60"
          mode: dropdown

    enable_switch:
      name: Enable Automation only when Heating
      description: Enable or disable the automation only when entity is on HEAT status
      default: true
      selector:
        boolean: {}

  source_url: https://github.com/davidepanato/ha-bp-tado-hj-control/blob/main/temp_sensor_calibration.yaml

variables:
  climate_entity: !input climate_entity
  entity_to_update: !input entity_to_update
  sensor_to_monitor: !input sensor_to_monitor
  enable_switch: !input enable_switch

trigger:
  # Automatic calibration at specified intervals (efficient - only runs when needed)
  - trigger: time_pattern
    minutes: !input time_interval_minutes
    id: calibrate

  # Manual push trigger (bypasses time and interval checks)
  - trigger: state
    entity_id: !input manual_trigger
    id: manual_push

action:
  - choose:
      # MANUAL PUSH - runs immediately, bypasses time/interval checks
      - conditions:
          - condition: trigger
            id: manual_push
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ enable_switch == false }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ enable_switch == true }}"
                  - condition: state
                    entity_id: !input climate_entity
                    attribute: hvac_action
                    state: heating
        sequence:
          - if:
              - condition: numeric_state
                entity_id:
                  - !input sensor_to_monitor
                value_template: >
                  {{ (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))|abs }}
                above: !input threshold
            then:
              - service: number.set_value
                data:
                  value: >
                    {{
                      ( states(entity_to_update)|float(0)
                        if states(entity_to_update) is not none else 0
                      )
                      +
                      (
                        (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))
                        if states(sensor_to_monitor) is not none and state_attr(climate_entity,'current_temperature') is not none
                        else 0
                      )
                      | round(1)
                    }}
                target:
                  entity_id: !input entity_to_update

      # AUTOMATIC CALIBRATION - respects time window and runs at specified intervals
      - conditions:
          - condition: trigger
            id: calibrate
          - condition: and
            conditions:
              - condition: time
                after: !input start_time
                before: !input end_time
              - condition: or
                conditions:
                  - condition: template
                    value_template: "{{ enable_switch == false }}"
                  - condition: and
                    conditions:
                      - condition: template
                        value_template: "{{ enable_switch == true }}"
                      - condition: state
                        entity_id: !input climate_entity
                        attribute: hvac_action
                        state: heating
        sequence:
          - if:
              - condition: numeric_state
                entity_id:
                  - !input sensor_to_monitor
                value_template: >
                  {{ (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))|abs }}
                above: !input threshold
            then:
              - service: number.set_value
                data:
                  value: >
                    {{
                      ( states(entity_to_update)|float(0)
                        if states(entity_to_update) is not none else 0
                      )
                      +
                      (
                        (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))
                        if states(sensor_to_monitor) is not none and state_attr(climate_entity,'current_temperature') is not none
                        else 0
                      )
                      | round(1)
                    }}
                target:
                  entity_id: !input entity_to_update

trace:
  stored_traces: 240
