blueprint:
  name: "TADO Hijack automatic update Entity Offset with Manual Push"
  description: >
    Update the offset value of a Tado offset number entity based on a temperature sensor.
    Uses cumulative offset calculation: new_offset = current_offset + (zigbee - tado_display).
    Includes: time window, efficient interval trigger, optional manual push,
    stale-sensor failsafe with optional manual override, and optional debug logging.
  domain: automation

  input:
    sensor_to_monitor:
      name: Zigbee Sensor to Monitor
      description: Temperature sensor used as the reference reading.
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    climate_entity:
      name: Tado Homekit Entity
      description: Tado climate entity providing current_temperature.
      selector:
        entity:
          domain: climate
          multiple: false

    entity_to_update:
      name: Tado Hijack offset entity
      description: Number entity that represents the Tado temperature offset.
      selector:
        entity:
          domain: number
          multiple: false

    manual_trigger:
      name: Manual Push Button (Optional)
      description: Create as Helper → Input button. Leave empty to disable manual push.
      default: ""
      selector:
        entity:
          domain: input_button
          multiple: false

    manual_ignore_failsafe:
      name: Manual push ignores failsafe (not recommended)
      description: If enabled, manual push can run even if the Zigbee sensor is stale/unavailable.
      default: false
      selector:
        boolean: {}

    sensor_max_age_minutes:
      name: Maximum Sensor Age (minutes)
      description: Block updates if Zigbee sensor hasn't updated recently.
      default: 15
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes
          mode: slider

    threshold:
      name: Threshold
      description: Minimum absolute temperature difference required to apply/update the offset (auto runs only).
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 10.0
          step: 0.5
          unit_of_measurement: °C
          mode: slider

    debug_logging:
      name: Debug logging
      description: If enabled, writes a logbook entry showing Zigbee temp, Tado temp, current offset, delta, and new offset.
      default: false
      selector:
        boolean: {}

    start_time:
      name: When the automation starts
      selector:
        time: {}

    end_time:
      name: When the automation stops
      selector:
        time: {}

    time_interval_minutes:
      name: Time Interval
      description: How often to run the calibration check.
      default: "/15"
      selector:
        select:
          options:
            - label: "Every 5 minutes"
              value: "/5"
            - label: "Every 10 minutes"
              value: "/10"
            - label: "Every 15 minutes"
              value: "/15"
            - label: "Every 20 minutes"
              value: "/20"
            - label: "Every 25 minutes"
              value: "/25"
            - label: "Every 30 minutes"
              value: "/30"
            - label: "Every 35 minutes"
              value: "/35"
            - label: "Every 40 minutes"
              value: "/40"
            - label: "Every 45 minutes"
              value: "/45"
            - label: "Every 50 minutes"
              value: "/50"
            - label: "Every 55 minutes"
              value: "/55"
            - label: "Every 60 minutes"
              value: "/60"
          mode: dropdown

  source_url: https://github.com/davidepanato/ha-bp-tado-hj-control/blob/main/temp_sensor_calibration.yaml

mode: single

variables:
  climate_entity: !input climate_entity
  entity_to_update: !input entity_to_update
  sensor_to_monitor: !input sensor_to_monitor
  sensor_max_age_minutes: !input sensor_max_age_minutes
  manual_ignore_failsafe: !input manual_ignore_failsafe
  manual_trigger: !input manual_trigger
  debug_logging: !input debug_logging

  zigbee_temp: "{{ states(sensor_to_monitor) | float(0) }}"
  tado_display_temp: "{{ state_attr(climate_entity, 'current_temperature') | float(0) }}"
  current_offset: "{{ states(entity_to_update) | float(0) }}"
  delta: "{{ (zigbee_temp - tado_display_temp) | round(1) }}"
  new_offset: "{{ (current_offset + delta) | round(1) }}"

trigger:
  - trigger: time_pattern
    minutes: !input time_interval_minutes
    id: calibrate

  - trigger: state
    entity_id: !input manual_trigger
    id: manual_push

action:
  - choose:
      # Manual push: applies offset immediately (no time window, no threshold, no heating check)
      - conditions:
          - condition: trigger
            id: manual_push
          - condition: template
            value_template: "{{ manual_trigger != '' }}"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ manual_ignore_failsafe }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ has_value(sensor_to_monitor) }}"
                  - condition: template
                    value_template: >
                      {% set s = states[sensor_to_monitor] if states[sensor_to_monitor] is defined else none %}
                      {% if s is none %}
                        false
                      {% else %}
                        {{ ((as_timestamp(now()) - as_timestamp(s.last_updated)) / 60) <= (sensor_max_age_minutes | float(0)) }}
                      {% endif %}
                  - condition: template
                    value_template: >
                      {% set hour_ago = states[sensor_to_monitor].last_changed if states[sensor_to_monitor] is defined else none %}
                      {% if hour_ago is none %}
                        false
                      {% else %}
                        {{ (as_timestamp(now()) - as_timestamp(hour_ago)) < 3600 }}
                      {% endif %}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ debug_logging }}"
                sequence:
                  - service: logbook.log
                    data:
                      name: "Tado offset debug"
                      message: >
                        Manual push. Zigbee={{ zigbee_temp }}, Tado={{ tado_display_temp }}, CurrentOffset={{ current_offset }}, Delta={{ delta }}, NewOffset={{ new_offset }}
          - service: number.set_value
            target:
              entity_id: !input entity_to_update
            data:
              value: "{{ new_offset }}"

      # Automatic calibration: respects threshold, time window
      - conditions:
          - condition: trigger
            id: calibrate
          - condition: template
            value_template: "{{ has_value(sensor_to_monitor) }}"
          - condition: template
            value_template: >
              {% set s = states[sensor_to_monitor] if states[sensor_to_monitor] is defined else none %}
              {% if s is none %}
                false
              {% else %}
                {{ ((as_timestamp(now()) - as_timestamp(s.last_updated)) / 60) <= (sensor_max_age_minutes | float(0)) }}
              {% endif %}
          - condition: template
            value_template: >
              {% set hour_ago = states[sensor_to_monitor].last_changed if states[sensor_to_monitor] is defined else none %}
              {% if hour_ago is none %}
                false
              {% else %}
                {{ (as_timestamp(now()) - as_timestamp(hour_ago)) < 3600 }}
              {% endif %}
          - condition: time
            after: !input start_time
            before: !input end_time
        sequence:
          - if:
              - condition: numeric_state
                entity_id: !input sensor_to_monitor
                value_template: >
                  {{ (states(sensor_to_monitor)|float(0) - state_attr(climate_entity,'current_temperature')|float(0))|abs }}
                above: !input threshold
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ debug_logging }}"
                    sequence:
                      - service: logbook.log
                        data:
                          name: "Tado offset debug"
                          message: >
                            Auto run. Zigbee={{ zigbee_temp }}, Tado={{ tado_display_temp }}, CurrentOffset={{ current_offset }}, Delta={{ delta }}, NewOffset={{ new_offset }}
              - service: number.set_value
                target:
                  entity_id: !input entity_to_update
                data:
                  value: "{{ new_offset }}"

trace:
  stored_traces: 240
